services:
  - type: web
    name: finance-tracker-backend
    env: node
    plan: starter
    repo: https://github.com/ManyaSamadhiya2107/financetracker
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://manyasamadhiya2004_db_user:m1a2n3y4a5@cluster0.ukxow3p.mongodb.net/?appName=Cluster0

  - type: static
    name: finance-tracker-frontend
    env: static
    plan: starter
    repo: https://github.com/ManyaSamadhiya2107/financetracker
    branch: main
    buildCommand: cd frontend && npm ci && npm run build
    publishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://finance-tracker-backend.onrender.com # update after backend deploy
